### ISSUE TITLE
Tests may hang

### ISSUE THREAD

**Issue by eserte** [dod38fr/config-model-itself#1] opened 2015-12-02 20:58 UTC
The t/cme-meta-plugin.t test of Config-Model-Itself-2.001 and 2.002 hangs on many of my smokers. The smoker systems have an X11 DISPLAY in a vnc server. If I attach into such a vnc server, then I can see a "cme meta edit fstab" window, and nothing happens. I have to select File > quit manually to proceed (but even this does not seem to work always).

Maybe there's a race condition and automatic quitting does not work?

**Comment by dod38fr** [comment] 2015-12-03 09:13
ack. This problem must be a PITA for you and other smoke tester. I'll upload a fix as soon as possible 

I think I'll just delay more the quit callback. I'd prefer run this callback when the widget is completely loaded, but as far as I know, there's no relevant Tk Event to use as a trigger...

All the best

**Comment by dod38fr** [comment] 2015-12-03 19:48
Unfortunately, I cannot reproduce this problem: I've run the tests (with `prove`), I've reduced the [delay](https://github.com/dod38fr/config-model-itself/blob/master/lib/App/Cme/Command/meta.pm#L354) that calls back [Config::Model::TkUI::quit](https://github.com/dod38fr/config-model-tk-ui/blob/master/lib/Config/Model/TkUI.pm#L468) to no avail: tests always work on my system (in or out of vnc). So I don't think that increasing this delay will change the test results. 

Unfortunately, I'm out of ideas...

BTW, when you select `File->quit` manually, does the test succeed ?

**Comment by eserte** [comment] 2015-12-03 22:06
I did a module version comparison of two perls, one where the test hanged and another with passing tests. One notable difference was Config::Model::TkUI: 1.347 in the hanging perl and 1.350 in the passing one. After upgrading the Config::Model::TkUI to the latest version it was passing in the previously hanging one, too.

Maybe also interesting: the newer Config::Model::TkUI seems to have a new dependency, Tk::DoubleClick. Unfortunately Tk::DoubleClick's test suite fails if Test::Pod::Coverage is installed (see https://rt.cpan.org/Ticket/Display.html?id=108422 ). This is probably the reason why many of my smoker perls still had the old Config::Model::TkUI installed.

**Comment by dod38fr** [comment] 2015-12-05 16:35
Thanks for the tip. With Tj::DoubleClick Author permission, I'm going to fix and update Tk::DoubleClick.

All the best

**Comment by dod38fr** [comment] 2016-01-27 19:59
Actually, this was not a problem with Tk::DoubleClick. THe bug was with the test_and_quit option: quit did not happen when save failed... This will be fixed with next release.

**Comment by dod38fr** [comment] 2016-01-27 20:04
fixed in v2.003

**Closed as completed by dod38fr** 2016-01-27 20:04 UTC
